- name: Check standard docker package is *not* installed
  sudo: yes
  dnf: name=docker state=absent

- { include: get-and-cache.yml, toget: "https://get.docker.com/rpm/1.7.0/fedora-22/RPMS/x86_64/docker-engine-1.7.0-1.fc22.x86_64.rpm" }

- name: Install Docker Package from Docker Inc
  sudo: yes
  dnf: name="{{ cached }}" state=present
  environment: proxy_env

- name: Create a docker group
  sudo: yes
  group: name=docker state=present
  tags: fast

- name: Add the current user to the docker group
  sudo: yes
  user: name="{{ user.name }}" groups=docker append=yes
  tags: fast

- name: Docker systemd configuration
  sudo: yes
  template: src=docker-systemd-config owner=root group=root dest=/usr/lib/systemd/system/docker.service
  notify:
   - restart docker
  tags: fast

- name: Docker config file
  sudo: yes
  template: src=docker-sysconfig owner=root group=root dest=/etc/sysconfig/docker
  notify:
   - restart docker
  tags: fast

- name: start and configure Docker
  service: name=docker state=started
  sudo: yes
  tags: fast

- { include: get-and-cache.yml, toget: "https://github.com/docker/machine/releases/download/v0.3.0/docker-machine_linux-amd64" }

- name: Install Docker machine
  sudo: yes
  copy: src="{{ cached }}" dest=/usr/local/bin/docker-machine
  environment: proxy_env

- name: Make Docker Machine executable
  sudo: yes
  file: path=/usr/local/bin/docker-machine state=file mode="u+rx,a+x,g+x"

- { include: get-and-cache.yml, toget: "https://github.com/docker/compose/releases/download/1.3.1/docker-compose-Linux-x86_64" }

- name: Install Docker Compose
  sudo: yes
  copy: src="{{ cached }}" dest=/usr/local/bin/docker-compose
  environment: proxy_env

- name: Make Docker Machine compose
  sudo: yes
  file: path=/usr/local/bin/docker-compose state=file mode="u+rx,a+x,g+x"
